import { Product } from "../types/index";

export const products: Product[] = [
  {
    id: "1",
    name: "Espresso",
    price: 80,
    description:
      "Yoğun aromaya sahip klasik İtalyan usulü espresso, özel çekilmiş taze kahve çekirdeklerinden hazırlanır.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "2",
    name: "Caffe Latte",
    price: 105,
    description:
      "Yumuşak ve kremsi bir içim sunan latte, espresso shot üzerine buharla ısıtılmış süt ve kremsi süt köpüğüyle hazırlanır.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "süt bazlı", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "3",
    name: "Americano",
    price: 95,
    description:
      "Double shot espresso üzerine sıcak su eklenerek hazırlanan kahve.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "4",
    name: "Cappuccino",
    price: 105,
    description:
      "Eşit oranda espresso, buharla ısıtılmış süt ve süt köpüğünden oluşan, İtalyan klasiği kahve.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "süt bazlı", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "5",
    name: "Filtre Kahve",
    price: 90,
    description:
      "Özenle seçilmiş çekirdeklerin damla damla demlenmesiyle hazırlanan, ayıltıcı ve aromatik bir kahve deneyimi.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "demleme", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "6",
    name: "Mocha",
    price: 115,
    description:
      "Espresso, sıcak çikolata ve buharla ısıtılmış sütün muhteşem birleşimi, üzerinde krema ile servis edilir.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "süt bazlı", "espresso bazlı", "şuruplu", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "8",
    name: "Türk Kahvesi",
    price: 80,
    description:
      "Geleneksel yöntemle cezve kullanılarak pişirilen, ince öğütülmüş taze kavrulmuş kahveden hazırlanan yoğun lezzetli Türk kahvesi.",
    image: "/assets/images/turkish-coffee.jpg",
    category: ["sıcak", "geleneksel", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "9",
    name: "Salep",
    price: 115,
    description:
      "Kıvılcımlı ve kremiş bir salep, sıcak ve soğuk içeceklerde harika bir tat verir.",
    image: "/assets/images/salep.jpg",
    category: ["sıcak", "süt bazlı"],
    mainCategory: "Sıcak İçecekler",
  },
  {
    id: "10",
    name: "Siyah Çay",
    price: 30,
    description: "Klasik siyah karadeniz çayı",
    image: "/assets/images/tea.jpg",
    category: ["sıcak", "çay"],
    mainCategory: "Çay",
  },
  {
    id: "11",
    name: "Hibiskus Çayı",
    price: 90,
    description: "Kurutulmuş hibiskus yapraklarıyla hazırlanan çay",
    image: "/assets/images/tea.jpg",
    category: ["sıcak", "bitki çayı", "çay"],
    mainCategory: "Çay",
  },
  {
    id: "12",
    name: "Sultan Çayı",
    price: 90,
    description:
      "Kurutulmuş meyvelerle ve faydalı bitkilerle hazırlanan şifa deposu çay",
    image: "/assets/images/tea.jpg",
    category: ["sıcak", "bitki çayı", "çay"],
    mainCategory: "Çay",
  },
  {
    id: "13",
    name: "Long Black",
    price: 95,
    description:
      "Sıcak su üzerine double shot espresso eklenerek hazırlanan kahve.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "14",
    name: "Espresso Doppio",
    price: 90,
    description:
      "Double shot espresso, klasik espresso içimine çok daha kuvvetli bir tat verir.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "15",
    name: "Cortado",
    price: 100,
    description:
      "Klasik espresso içimine çok daha yumuşak bir tat katmak için süt köpüğü eklenir.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "espresso bazlı", "süt bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "16",
    name: "Flat White",
    price: 105,
    description:
      "Klasik espresso içimine çok daha yumuşak bir tat katmak için sıcak süt eklenir.",
    image: "/assets/images/hot-coffee.jpg",
    category: ["sıcak", "espresso bazlı", "süt bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "18",
    name: "Iced Americano",
    price: 110,
    description:
      "Taze çekilmiş espresso üzerine soğuk su ve buz eklenerek hazırlanan ferahlatıcı kahve.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["soğuk", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "19",
    name: "Iced Latte",
    price: 115,
    description:
      "Espresso, soğuk süt ve buz ile hazırlanan, yaz aylarının vazgeçilmez serinleticisi.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["soğuk", "süt bazlı", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "20",
    name: "Frappuccino",
    price: 120,
    description:
      "Kahve, süt, buz ve şeker karışımının blenderdan geçirilmesiyle hazırlanan, krema ile servis edilen tatlı buzlu içecek.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["soğuk", "süt bazlı", "blended", "şuruplu", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "21",
    name: "Affogato",
    price: 120,
    description:
      "Vanilyalı dondurma üzerine sıcak espresso dökülerek servis edilen İtalyan tatlı içeceği.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["soğuk", "tatlı", "espresso bazlı", "süt bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "22",
    name: "Iced Mocha",
    price: 120,
    description:
      "Espresso, çikolata şurubu, soğuk süt ve buz parçaları ile hazırlanan, üzeri çikolata sosu ve krema ile süslenen tatlandırılmış buzlu kahve.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["soğuk", "süt bazlı", "espresso bazlı", "şuruplu", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "23",
    name: "Iced Cappuccino",
    price: 115,
    description:
      "Espresso, soğuk süt ve buz ile hazırlanan, yaz aylarının vazgeçilmez serinleticisi.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["soğuk", "süt bazlı", "espresso bazlı", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "24",
    name: "Chocochino",
    price: 125,
    description:
      "Sıcak çikolata, süt ve espresso ile hazırlanan tatlandırılmış kahve.",
    image: "/assets/images/cold-coffee.jpg",
    category: ["sıcak", "süt bazlı", "şuruplu", "kahve"],
    mainCategory: "Kahve",
  },
  {
    id: "25",
    name: "Nesfit",
    price: 45,
    description: "Sağlıklı ve lezzetli tahıllı bisküvi",
    image: "/assets/images/dessert.jpg",
    category: ["tatlı", "bisküvi"],
    mainCategory: "Atıştırmalık",
  },
  {
    id: "26",
    name: "Tambol Çikolata",
    price: 95,
    description: "Sütlü çikolata kaplı fındıklı gofret",
    image: "/assets/images/dessert.jpg",
    category: ["tatlı", "çikolata"],
    mainCategory: "Atıştırmalık",
  },
  {
    id: "27",
    name: "Tek Pasta",
    price: 180,
    description: "Günlük taze hazırlanan dilim pasta",
    image: "/assets/images/dessert.jpg",
    category: ["tatlı", "pasta"],
    mainCategory: "Tatlı",
  },
  {
    id: "28",
    name: "Magnolia",
    price: 160,
    description: "Özel tarif ile hazırlanan sütlü tatlı",
    image: "/assets/images/dessert.jpg",
    category: ["tatlı", "sütlü"],
    mainCategory: "Tatlı",
  },
  {
    id: "29",
    name: "Profiterol",
    price: 160,
    description: "Özel tarif ile hazırlanan çikolatalı tatlı",
    image: "/assets/images/dessert.jpg",
    category: ["tatlı", "çikolata"],
    mainCategory: "Tatlı",
  },
  {
    id: "30",
    name: "Su",
    price: 35,
    description: "Cam şişe su",
    image: "/assets/images/dessert.jpg",
    category: ["içecek"],
    mainCategory: "İçecek",
  },
  {
    id: "31",
    name: "Soda",
    price: 50,
    description: "Sade, Karadutlu, Mango-Ananaslı, Karpuz-Çilekli",
    image: "/assets/images/soda.jpg",
    category: ["içecek"],
    mainCategory: "İçecek",
  },
  {
    id: "32",
    name: "Kola",
    price: 75,
    description: "Kola, Fanta, Sprite",
    image: "/assets/images/soda.jpg",
    category: ["içecek"],
    mainCategory: "İçecek",
  },
];
